function featureColumnNames = getImportantMelFeatureNames()
% getImportantMelFeatureNames
% Return descriptive names for 16 features:
% 1) spectral/timbral level features -> 4
% 2) spectral variability features   -> 4
% 3) temporal dynamics features      -> 4
% 4) harmonic features               -> 4

featureColumnNames = { ...
    'timbral_log_mel_mean', ...
    'timbral_log_mel_median', ...
    'timbral_band_energy_spread', ...
    'timbral_frame_peak_mean', ...
    'variability_log_mel_std_global', ...
    'variability_band_std_mean', ...
    'variability_frame_energy_std', ...
    'variability_band_range_mean', ...
    'temporal_frame_energy_delta_abs_mean', ...
    'temporal_frame_energy_delta_std', ...
    'temporal_zero_crossing_rate_mean', ...
    'temporal_rms_std', ...
    'harmonic_voiced_frame_ratio', ...
    'harmonic_f0_mean_hz', ...
    'harmonic_f0_std_hz', ...
    'harmonic_energy_ratio_mean'};
end
