function featureCategories = getFeatureCategoryDefinitions()
% getFeatureCategoryDefinitions
% Define the four feature groups used in the feature CSV.

featureCategories = struct( ...
    'directoryName', {}, ...
    'displayName', {}, ...
    'featureNames', {});

featureCategories(1).directoryName = 'spectral_timbral_level';
featureCategories(1).displayName = 'Spectral Timbral Level';
featureCategories(1).featureNames = { ...
    'timbral_log_mel_mean', ...
    'timbral_log_mel_median', ...
    'timbral_band_energy_spread', ...
    'timbral_frame_peak_mean'};

featureCategories(2).directoryName = 'spectral_variability';
featureCategories(2).displayName = 'Spectral Variability';
featureCategories(2).featureNames = { ...
    'variability_log_mel_std_global', ...
    'variability_band_std_mean', ...
    'variability_frame_energy_std', ...
    'variability_band_range_mean'};

featureCategories(3).directoryName = 'temporal_dynamics';
featureCategories(3).displayName = 'Temporal Dynamics';
featureCategories(3).featureNames = { ...
    'temporal_frame_energy_delta_abs_mean', ...
    'temporal_frame_energy_delta_std', ...
    'temporal_zero_crossing_rate_mean', ...
    'temporal_rms_std'};

featureCategories(4).directoryName = 'harmonic';
featureCategories(4).displayName = 'Harmonic';
featureCategories(4).featureNames = { ...
    'harmonic_voiced_frame_ratio', ...
    'harmonic_f0_mean_hz', ...
    'harmonic_f0_std_hz', ...
    'harmonic_energy_ratio_mean'};
end
